module.exports = {
  apps: [
    {
      name: "ospain2",
      cwd: "../OSPAiN2-hub",
      script: "npm",
      args: "start",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      env_development: {
        NODE_ENV: "development",
        args: "run dev",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/ospain2-error.log",
      out_file: "../logs/ospain2-out.log",
      merge_logs: true,
    },
    {
      name: "knowledge-graph",
      cwd: "../mcp-knowledge-graph",
      script: "node",
      args: "dist/index.js --memory-path ../../data/memory.jsonl",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/knowledge-graph-error.log",
      out_file: "../logs/knowledge-graph-out.log",
      merge_logs: true,
    },
    {
      name: "knowledge-graph-health",
      script: "./knowledge-graph-health-check.js",
      instances: 1,
      autorestart: true,
      watch: false,
      cron_restart: "*/15 * * * *", // Check every 15 minutes
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/kg-health-error.log",
      out_file: "../logs/kg-health-out.log",
      merge_logs: true,
    },
    {
      name: "mcp-server",
      cwd: "..",
      script: "python",
      args: "mcp_server.py",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/mcp-server-error.log",
      out_file: "../logs/mcp-server-out.log",
      merge_logs: true,
    },
    {
      name: "mcp-server-health",
      script: "./mcp-server-health-check.js",
      instances: 1,
      autorestart: true,
      watch: false,
      cron_restart: "*/15 * * * *", // Check every 15 minutes
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/mcp-health-error.log",
      out_file: "../logs/mcp-health-out.log",
      merge_logs: true,
    },
  ],
};
